-- Create users table
CREATE TABLE IF NOT EXISTS users (
  CODUSER INT(7) PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  imguser VARCHAR(50) DEFAULT '',
  role VARCHAR(10) DEFAULT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  mobile BIGINT(10) NOT NULL,
  cuidador TINYINT(1) DEFAULT 0,
  profesional TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create docentes table
CREATE TABLE IF NOT EXISTS docentes (
  CODDOCENTE INT(11) PRIMARY KEY AUTO_INCREMENT,
  NOMDOCENTE VARCHAR(50) DEFAULT NULL,
  CVDOCENTE TEXT DEFAULT NULL,
  EMAIL VARCHAR(80) DEFAULT NULL,
  ESPECIALIDAD VARCHAR(80) DEFAULT NULL,
  TELEFONO VARCHAR(12) DEFAULT NULL,
  RUTDOCENTE VARCHAR(12) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create actividades table
CREATE TABLE IF NOT EXISTS actividades (
  CODACTIVIDAD INT(7) PRIMARY KEY AUTO_INCREMENT,
  NOMACTIVIDAD VARCHAR(100) DEFAULT NULL,
  FECACTIVIDAD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SHORTDESCRIPTION VARCHAR(150) DEFAULT NULL,
  TIPACTIVIDAD INT(4) DEFAULT NULL,
  DESCRIPCION TEXT DEFAULT NULL,
  CERTIFICADO TEXT DEFAULT NULL,
  ENTREGABLE TEXT DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create modulos table
CREATE TABLE IF NOT EXISTS modulos (
  CODMODULO INT(7) PRIMARY KEY AUTO_INCREMENT,
  NOMMODULO VARCHAR(50) DEFAULT NULL,
  CONTENIDOS TEXT DEFAULT NULL,
  CODDOCENTE INT(4) DEFAULT NULL,
  CODACTIVIDAD INT(7) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (CODDOCENTE) REFERENCES docentes(CODDOCENTE) ON DELETE SET NULL,
  FOREIGN KEY (CODACTIVIDAD) REFERENCES actividades(CODACTIVIDAD) ON DELETE SET NULL
);

-- Create modact table (junction table if needed)
CREATE TABLE IF NOT EXISTS modact (
  CODMODACT INT(7) PRIMARY KEY AUTO_INCREMENT,
  CODMODULO INT(7) DEFAULT NULL,
  CODACTIVIDAD INT(7) DEFAULT NULL,
  FOREIGN KEY (CODMODULO) REFERENCES modulos(CODMODULO) ON DELETE CASCADE,
  FOREIGN KEY (CODACTIVIDAD) REFERENCES actividades(CODACTIVIDAD) ON DELETE CASCADE
);

-- Create participantes table
CREATE TABLE IF NOT EXISTS participantes (
  CODPARTICIPANTE INT(11) PRIMARY KEY AUTO_INCREMENT,
  CODUSER INT(7) NOT NULL,
  CODACTIVIDAD INT(7) NOT NULL,
  ASISTENCIA DECIMAL(10,0) NOT NULL DEFAULT 0,
  CERTIFICADO VARCHAR(100) NOT NULL DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (CODUSER) REFERENCES users(CODUSER) ON DELETE CASCADE,
  FOREIGN KEY (CODACTIVIDAD) REFERENCES actividades(CODACTIVIDAD) ON DELETE CASCADE
);